package scrape

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/gastownhall/gascity/internal/codegraph/facts"
)

func TestEncoreClientScraper(t *testing.T) {
	dir := t.TempDir()
	clientPath := filepath.Join(dir, "client.ts")
	// Matches the real Encore v1.56.6 generated client shape:
	// export namespace <svc> { ... export class ServiceClient { ...
	//   public async <Method>(params): Promise<...> { ... } } }
	src := `
// Code generated by the Encore v1.56.6 client generator. DO NOT EDIT.
export namespace auth {
    export interface LoginParams {}
    export interface LoginResponse {}
    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.Login = this.Login.bind(this)
            this.Logout = this.Logout.bind(this)
        }

        public async Login(params: LoginParams): Promise<LoginResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", ` + "`/auth/login`" + `, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        public async Logout(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", ` + "`/auth/logout`" + `)
        }
    }
}
export namespace work {
    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.GetOrders = this.GetOrders.bind(this)
        }

        public async GetOrders(filter: Filter): Promise<Order[]> {
            const resp = await this.baseClient.callTypedAPI("GET", ` + "`/work/orders`" + `)
            return await resp.json() as Order[]
        }
    }
}
`
	if err := os.WriteFile(clientPath, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}

	endpoints, err := ScanEncoreClient(clientPath)
	if err != nil {
		t.Fatal(err)
	}
	if len(endpoints) != 3 {
		t.Fatalf("got %d endpoints, want 3 (%+v)", len(endpoints), endpoints)
	}
	wantURNs := map[string]bool{
		"endpoint:auth.Login":     true,
		"endpoint:auth.Logout":    true,
		"endpoint:work.GetOrders": true,
	}
	for _, e := range endpoints {
		if !wantURNs[e.URN] {
			t.Errorf("unexpected endpoint URN %q", e.URN)
		}
		if e.Kind != facts.KindEndpoint {
			t.Errorf("kind = %q", e.Kind)
		}
	}
}

func TestScanCallSites(t *testing.T) {
	dir := t.TempDir()
	caller := filepath.Join(dir, "Login.tsx")
	if err := os.WriteFile(caller, []byte(`
import { client } from './client';

export function LoginScreen() {
    const onSubmit = async () => {
        await client.auth.Login({ email, password });
        navigate('/');
    };
}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	edges, err := ScanCallSites(caller, "fe", []string{"client"})
	if err != nil {
		t.Fatal(err)
	}
	if len(edges) != 1 {
		t.Fatalf("got %d edges, want 1 (%+v)", len(edges), edges)
	}
	if edges[0].DstURN != "endpoint:auth.Login" {
		t.Errorf("DstURN = %q", edges[0].DstURN)
	}
}
